import { Inter } from "next/font/google";
import "./globals.css";
import "./main.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  charset: "UTF-8",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header className="main">
          <h1>나의 NextJS Page</h1>
          <div>
            <input />
          </div>
        </header>
        <nav className="main">
          <div>
            <Link href="/">Home</Link>
          </div>
          <div>
            <Link href="/bbs/notice">공지사항</Link>
          </div>
          <div>
            <Link href="/bbs/free">자유게시판</Link>
          </div>
          <div>
            <Link href="/user/login">로그인</Link>
          </div>
          <div>
            <Link href="/user/join">회원가입</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
