import { Inter } from "next/font/google";
import "./globals.css";
import "./main.css";
import Nav from "@/comps/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  charset: "UTF-8",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header className="main">
          <h1>나의 NextJS Page</h1>
          <div>
            <input />
          </div>
        </header>
        <Nav />
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
